# Agenda

1. topics
    * everything up to the class on basic postgres
    * we only made it halfway through the slides (types, `CREATE`, but not really `SELECT`, `UPDATE`, `INSERT`, etc.)
        * broad db stuff
        * high level postgres
        * db material will not be written - MC, ordering, MS, FIB, TF ... very short, mostly conceptual
    * encoding, dealing with csvs, etc.
    * basic python, comprehensions, classes
2. format of the exam
    * fib, syntactically correct
        * one "word" no spaces
        * s = "foo,bar"
        * s.split("___A___")
        * copy and paste the code
        * fill in blanks
        * run it
    * coding questions: partial credit, even if it doesn't run
        * credit for attempt
    * brightspace
    * 1/4 to 1/2 of points will be in the form of written
        * rolling sales... graph the relationship between sq ft and price
        * top 3 neighborhoods by number of sales
        * 1 longer form coding question: write a class that does x
        * write a function that does x
    * order shortest to longest... points are apparent on each page
    * the instructions at the start will contain a link to a dataset
        * stats.nba.com ... from 2020-2021 season
        * posted on edstem after class: dataset + dictionary
        * in class discussion on this as well!
    * ~10 mc/ms/tf/simple ordering/fib
    * ~2-3 longer fill in the blank
    * ~5 coding questions (pandas)
    * ~1 coding question
3. scheduling
    * 2 options - if you miss, you get a zero
        1. in class during regular time (< class time, start 5 min in, end 5 min early)
        2. 9pm on Thursday (next day, but evening)
        3. if you're async and want regular time... send note on edstem with nikita cc'd (instructors)j
4. dataset X
5. any of your questions <---
    * X data on the web
        * json 
        * html
        * requests
        * beautiful soup
    * X sql
    * regex
        * match
    * df stuff
        * filtering / indexing
        * [] vs loc vs iloc
    * comp and gen
        * list comp
        * generators
    * agg
        * groupby
        * sort after agg
    * matplotlib
    * lambda
    * numpy broadcasting
    * merge
    * rename
    * fillna
    * map

guard <-- shorter
forward
center <-- taller

guard-forward
forward-guard


`POSITION`
`G, F, C, G-F, F-G, C-F, C-G`

In [1]:
import pandas as pd
import numpy as np
import re
import json
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('./players2020.csv')

In [3]:
df

,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,POSITION,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,PTS,REB,AST,FROM_YEAR,TO_YEAR
0,Achiuwa,Precious,Miami,Heat,MIA,F,"6'8""",225 lbs,Memphis,Nigeria,2020.0,1.0,20.0,1.0,5.8,3.9,0.5,2020,2020
1,Adams,Jaylen,Portland,Trail Blazers,POR,G,"6'0""",225 lbs,St. Bonaventure,USA,NaN,NaN,NaN,NaN,0.3,0.4,0.3,2018,2020
2,Adams,Steven,New Orleans,Pelicans,NOP,C,"6'11""",265 lbs,Pittsburgh,New Zealand,2013.0,1.0,12.0,1.0,8.2,9.2,2.0,2013,2020
3,Adebayo,Bam,Miami,Heat,MIA,C-F,"6'9""",255 lbs,Kentucky,USA,2017.0,1.0,14.0,1.0,19.2,9.5,5.4,2017,2020
4,Aldridge,LaMarcus,San Antonio,Spurs,SAS,C-F,"6'11""",250 lbs,Texas,USA,2006.0,1.0,2.0,1.0,13.7,4.5,1.7,2006,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,Wright,Delon,Detroit,Pistons,DET,G,"6'5""",185 lbs,Utah,USA,2015.0,1.0,20.0,1.0,10.6,4.5,4.8,2015,2020
493,Young,Thaddeus,Chicago,Bulls,CHI,F,"6'8""",235 lbs,Georgia Tech,USA,2007.0,1.0,12.0,1.0,12.2,6.1,4.3,2007,2020
494,Young,Trae,Atlanta,Hawks,ATL,G,"6'1""",180 lbs,Oklahoma,USA,2018.0,1.0,5.0,1.0,26.7,4.1,9.3,2018,2020
495,Zeller,Cody,Charlotte,Hornets,CHA,F-C,"6'11""",240 lbs,Indiana,USA,2013.0,1.0,4.0,1.0,10.0,7.5,2.3,2013,2020
496,Zubac,Ivica,LA,Clippers,LAC,C,"7'0""",240 lbs,Mega Basket,Croatia,2016.0,2.0,32.0,1.0,8.2,6.9,1.1,2016,2020

In [4]:
res = requests.get('http://linserv1.cims.nyu.edu:10000/films?_page=1')

In [7]:
res.status_code

200

In [18]:
# res.content is result of http request
# you can also read json from a file
# or just pass in a string
json.loads('{"foo": 1}')
json.loads(res.content) 
# res.text # string
# res.content # bytes object representing response
res.json()[:1] # this returns parsed json

[{'id': '2baf70d1-42bb-4437-b551-e5fed5a87abe',
  'title': 'Castle in the Sky',
  'original_title': '天空の城ラピュタ',
  'original_title_romanised': 'Tenkū no shiro Rapyuta',
  'description': "The orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world.",
  'director': 'Hayao Miyazaki',
  'producer': 'Isao Takahata',
  'release_date': '1986',
  'running_time': '124',
  'rt_score': '95',
  'people': ['https://ghibliapi.herokuapp.com/people/'],
  'species': ['https://ghibliapi.herokuapp.com/species/af3910a6-429f-4c74-9ad5-dfe1c4aa04f2'],
  'locations': ['https://ghibliapi.herokuapp.com/locations/'],
  'vehicles': ['https://ghibliapi.herokuapp.com/vehicles/'],
  'url': 'https://ghibliapi.herokuapp.com/films/2baf70d1-42bb-4437-b551-e5fed5a87abe'}]

In [19]:
f = open('foo.json', 'r')
s = f.read()

In [20]:
type(s)

str

In [21]:
s

'{"foo":24}'

In [23]:
# s['foo'] # type error

In [24]:
json.loads(s)

{'foo': 24}

In [25]:
dom = BeautifulSoup(open('foo.html'))

In [26]:
dom

<html>
<body>
<p>foo</p>
</body>
</html>

In [27]:
dom = BeautifulSoup(open('foo.html').read())

In [28]:
dom

<html>
<body>
<p>foo</p>
</body>
</html>

In [29]:

dom = BeautifulSoup("<p>will this work?</p>")

In [30]:
dom

In [33]:
dom = BeautifulSoup(requests.get('https://www.nba.com/players').content)

In [36]:
#dom

In [39]:
t = dom.select_one('.players-list')

In [45]:
t.select('td div')
for div in t.select('td div'):
    img_dom = div.select('img')
    print(img_dom[0]['alt'])

Precious Achiuwa Headshot

IndexError: list index out of range

server / client architecture

what's an example of a client

psql (commandline client)
DataGrip
PGAdmin

```
psql \ commands
\l - list all databases
\d - show all objects (sequences, tables) in database
\dt - show only tables
\d some_object - describe the table or sequence

^^^^ this is not SQL
```

SQL

* case insensitive kw:
     SELECT, select
* identifiers - if quoted case sensitive
* we define what we want: declarative language

```
SELECT foo, bar FROM baz;

`CREATE`
create table table_name(col coltype, col coltype);

SELECT - reading / filtering
UPDATE - updates data in row / rows
DELETE - removes row / rows
ALTER - alter columns, tables, etc.
```

* numeric
    * decimal, numeric ... exact calculations
    * real,  ... floating point, but not exact
    * bigint
    * int
    * smallint
        * vary by number of bytes and values to accommodate
    * serial and bigserial autoincrementing
* text 
    * varchar <--- specify max number
    * text <--- unlimited number of characters
* datetime
    * timestamptz use the one w/ timezone
* other
    * money (currency)
    * ip address

In [50]:
import re

re.match
re.search
re.findall

dir(re)

['A',
 'ASCII',
 'DEBUG',
 'DOTALL',
 'I',
 'IGNORECASE',
 'L',
 'LOCALE',
 'M',
 'MULTILINE',
 'Match',
 'Pattern',
 'RegexFlag',
 'S',
 'Scanner',
 'T',
 'TEMPLATE',
 'U',
 'UNICODE',
 'VERBOSE',
 'X',
 '_MAXCACHE',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_cache',
 '_compile',
 '_compile_repl',
 '_expand',
 '_locale',
 '_pickle',
 '_special_chars_map',
 '_subx',
 'compile',
 'copyreg',
 'enum',
 'error',
 'escape',
 'findall',
 'finditer',
 'fullmatch',
 'functools',
 'match',
 'purge',
 'search',
 'split',
 'sre_compile',
 'sre_parse',
 'sub',
 'subn',
 'template']

In [51]:
df

,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,POSITION,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,PTS,REB,AST,FROM_YEAR,TO_YEAR
0,Achiuwa,Precious,Miami,Heat,MIA,F,"6'8""",225 lbs,Memphis,Nigeria,2020.0,1.0,20.0,1.0,5.8,3.9,0.5,2020,2020
1,Adams,Jaylen,Portland,Trail Blazers,POR,G,"6'0""",225 lbs,St. Bonaventure,USA,NaN,NaN,NaN,NaN,0.3,0.4,0.3,2018,2020
2,Adams,Steven,New Orleans,Pelicans,NOP,C,"6'11""",265 lbs,Pittsburgh,New Zealand,2013.0,1.0,12.0,1.0,8.2,9.2,2.0,2013,2020
3,Adebayo,Bam,Miami,Heat,MIA,C-F,"6'9""",255 lbs,Kentucky,USA,2017.0,1.0,14.0,1.0,19.2,9.5,5.4,2017,2020
4,Aldridge,LaMarcus,San Antonio,Spurs,SAS,C-F,"6'11""",250 lbs,Texas,USA,2006.0,1.0,2.0,1.0,13.7,4.5,1.7,2006,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,Wright,Delon,Detroit,Pistons,DET,G,"6'5""",185 lbs,Utah,USA,2015.0,1.0,20.0,1.0,10.6,4.5,4.8,2015,2020
493,Young,Thaddeus,Chicago,Bulls,CHI,F,"6'8""",235 lbs,Georgia Tech,USA,2007.0,1.0,12.0,1.0,12.2,6.1,4.3,2007,2020
494,Young,Trae,Atlanta,Hawks,ATL,G,"6'1""",180 lbs,Oklahoma,USA,2018.0,1.0,5.0,1.0,26.7,4.1,9.3,2018,2020
495,Zeller,Cody,Charlotte,Hornets,CHA,F-C,"6'11""",240 lbs,Indiana,USA,2013.0,1.0,4.0,1.0,10.0,7.5,2.3,2013,2020
496,Zubac,Ivica,LA,Clippers,LAC,C,"7'0""",240 lbs,Mega Basket,Croatia,2016.0,2.0,32.0,1.0,8.2,6.9,1.1,2016,2020

In [53]:
#df['PLAYER_LAST_NAME'].str.replace('regex', 'replacement', regex=True)
#df['PLAYER_LAST_NAME'].str.extract('regex with group')

In [54]:
import re
s = 'Joe Versoza jjv222 room #423'
re.search('ers', s)

In [56]:
re.findall('o\w', s)

['oe', 'oz', 'oo']

character classes:

* `[^a] - not an a
* `[a|b]` - a or b
* `[0-9]` - 0 through 9
* `[a-z]` - lowercase a - z
* `.` - any character (except newlines)
* `\d` - digit [0-9]
* `\s` - space character
* `\w` - word character  [0-9A-Za-z_]

In [57]:
re.findall('a[a-z]', 'aT')

[]

In [58]:

re.search('a[a-z]', 'at')

In [59]:

re.search('a[a|b]', 'at')

In [62]:

#re.search('a[a|b]', 'ab')
re.search('a[abc]', 'ac')

In [63]:
pattern = re.compile('\w\w\w\d\d\d')

In [67]:
re.search(pattern, s)

In [74]:
pattern = re.compile('(\w{3})(\d+)')

In [76]:
m = re.search(pattern, s)

In [80]:
m[2]

'222'

In [81]:
df

,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,POSITION,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,PTS,REB,AST,FROM_YEAR,TO_YEAR
0,Achiuwa,Precious,Miami,Heat,MIA,F,"6'8""",225 lbs,Memphis,Nigeria,2020.0,1.0,20.0,1.0,5.8,3.9,0.5,2020,2020
1,Adams,Jaylen,Portland,Trail Blazers,POR,G,"6'0""",225 lbs,St. Bonaventure,USA,NaN,NaN,NaN,NaN,0.3,0.4,0.3,2018,2020
2,Adams,Steven,New Orleans,Pelicans,NOP,C,"6'11""",265 lbs,Pittsburgh,New Zealand,2013.0,1.0,12.0,1.0,8.2,9.2,2.0,2013,2020
3,Adebayo,Bam,Miami,Heat,MIA,C-F,"6'9""",255 lbs,Kentucky,USA,2017.0,1.0,14.0,1.0,19.2,9.5,5.4,2017,2020
4,Aldridge,LaMarcus,San Antonio,Spurs,SAS,C-F,"6'11""",250 lbs,Texas,USA,2006.0,1.0,2.0,1.0,13.7,4.5,1.7,2006,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,Wright,Delon,Detroit,Pistons,DET,G,"6'5""",185 lbs,Utah,USA,2015.0,1.0,20.0,1.0,10.6,4.5,4.8,2015,2020
493,Young,Thaddeus,Chicago,Bulls,CHI,F,"6'8""",235 lbs,Georgia Tech,USA,2007.0,1.0,12.0,1.0,12.2,6.1,4.3,2007,2020
494,Young,Trae,Atlanta,Hawks,ATL,G,"6'1""",180 lbs,Oklahoma,USA,2018.0,1.0,5.0,1.0,26.7,4.1,9.3,2018,2020
495,Zeller,Cody,Charlotte,Hornets,CHA,F-C,"6'11""",240 lbs,Indiana,USA,2013.0,1.0,4.0,1.0,10.0,7.5,2.3,2013,2020
496,Zubac,Ivica,LA,Clippers,LAC,C,"7'0""",240 lbs,Mega Basket,Croatia,2016.0,2.0,32.0,1.0,8.2,6.9,1.1,2016,2020

In [88]:
df['TEAM_CITY'].str.replace('\w{3} ', 'Foo ', regex=True)
df['TEAM_CITY'].str.extract('(\w{3}) ').values

array([[nan],
       [nan],
       ['New'],
       [nan],
       ['San'],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['San'],
       [nan],
       [nan],
       ['den'],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['New'],
       [nan],
       [nan],
       ['Los'],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       ['Los'],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       ['San'],
       [nan],
       ['New'],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['oma'],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['oma'],
       [nan],
       [nan],
       ['Los'],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       ['San'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       ['oma'],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['oma'],
       ['San'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       ['den'],
       ['San'],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['San'],
       [nan],
       ['oma'],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       ['oma'],
       [nan],
       [nan],
       ['New'],
       [nan],
       ['oma'],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       [nan],
       ['Los'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       ['New'],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       ['San'],
       [nan],
       [nan],
       ['den'],
       [nan],
       ['oma'],
       [nan],
       [nan],
       [nan],
       ['New'],
       [nan],
       [nan],
       [nan],
       [nan],
       ['den'],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]], dtype=object)

array(['Miami', 'Portland', 'New Orleans', 'San Antonio', 'Phoenix',
       'Memphis', 'Cleveland', 'Orlando', 'Milwaukee', 'Los Angeles',
       'Toronto', 'Chicago', 'Washington', 'Utah', 'Sacramento',
       'Charlotte', 'New York', 'Denver', 'LA', 'Golden State',
       'Oklahoma City', 'Minnesota', 'Detroit', 'Dallas', 'Indiana',
       'Atlanta', nan, 'Philadelphia', 'Brooklyn', 'Boston', 'Houston'],
      dtype=object)

In [92]:
s = '\\wat now?'

In [93]:
s

'\\wat now?'

In [94]:
print(s)

\wat now?

In [98]:
re.findall('\\\w', s)
re.findall(r'\\w', s) # <--- treats \ as actual backslash

['\\w']

In [99]:
df

,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,POSITION,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,PTS,REB,AST,FROM_YEAR,TO_YEAR
0,Achiuwa,Precious,Miami,Heat,MIA,F,"6'8""",225 lbs,Memphis,Nigeria,2020.0,1.0,20.0,1.0,5.8,3.9,0.5,2020,2020
1,Adams,Jaylen,Portland,Trail Blazers,POR,G,"6'0""",225 lbs,St. Bonaventure,USA,NaN,NaN,NaN,NaN,0.3,0.4,0.3,2018,2020
2,Adams,Steven,New Orleans,Pelicans,NOP,C,"6'11""",265 lbs,Pittsburgh,New Zealand,2013.0,1.0,12.0,1.0,8.2,9.2,2.0,2013,2020
3,Adebayo,Bam,Miami,Heat,MIA,C-F,"6'9""",255 lbs,Kentucky,USA,2017.0,1.0,14.0,1.0,19.2,9.5,5.4,2017,2020
4,Aldridge,LaMarcus,San Antonio,Spurs,SAS,C-F,"6'11""",250 lbs,Texas,USA,2006.0,1.0,2.0,1.0,13.7,4.5,1.7,2006,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,Wright,Delon,Detroit,Pistons,DET,G,"6'5""",185 lbs,Utah,USA,2015.0,1.0,20.0,1.0,10.6,4.5,4.8,2015,2020
493,Young,Thaddeus,Chicago,Bulls,CHI,F,"6'8""",235 lbs,Georgia Tech,USA,2007.0,1.0,12.0,1.0,12.2,6.1,4.3,2007,2020
494,Young,Trae,Atlanta,Hawks,ATL,G,"6'1""",180 lbs,Oklahoma,USA,2018.0,1.0,5.0,1.0,26.7,4.1,9.3,2018,2020
495,Zeller,Cody,Charlotte,Hornets,CHA,F-C,"6'11""",240 lbs,Indiana,USA,2013.0,1.0,4.0,1.0,10.0,7.5,2.3,2013,2020
496,Zubac,Ivica,LA,Clippers,LAC,C,"7'0""",240 lbs,Mega Basket,Croatia,2016.0,2.0,32.0,1.0,8.2,6.9,1.1,2016,2020

In [103]:
df.loc[[2, 3], ['PLAYER_LAST_NAME', 'TEAM_CITY']]
# numpy indexing... rows, then columns
# off an attribute called loc
# loc is by label
# but label

  PLAYER_LAST_NAME    TEAM_CITY
2            Adams  New Orleans
3          Adebayo        Miami

In [102]:
df.iloc[[2, 3]]

,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,POSITION,HEIGHT,WEIGHT,COLLEGE,COUNTRY,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,PTS,REB,AST,FROM_YEAR,TO_YEAR
2,Adams,Steven,New Orleans,Pelicans,NOP,C,"6'11""",265 lbs,Pittsburgh,New Zealand,2013.0,1.0,12.0,1.0,8.2,9.2,2.0,2013,2020
3,Adebayo,Bam,Miami,Heat,MIA,C-F,"6'9""",255 lbs,Kentucky,USA,2017.0,1.0,14.0,1.0,19.2,9.5,5.4,2017,2020

In [106]:
df[['PLAYER_LAST_NAME', 'TEAM_CITY']]

    PLAYER_LAST_NAME    TEAM_CITY
0            Achiuwa        Miami
1              Adams     Portland
2              Adams  New Orleans
3            Adebayo        Miami
4           Aldridge  San Antonio
..               ...          ...
492           Wright      Detroit
493            Young      Chicago
494            Young      Atlanta
495           Zeller    Charlotte
496            Zubac           LA

[497 rows x 2 columns]

In [107]:
df.loc[2]

PLAYER_LAST_NAME           Adams
PLAYER_FIRST_NAME         Steven
TEAM_CITY            New Orleans
TEAM_NAME               Pelicans
TEAM_ABBREVIATION            NOP
POSITION                       C
HEIGHT                     6'11"
WEIGHT                   265 lbs
COLLEGE               Pittsburgh
COUNTRY              New Zealand
DRAFT_YEAR                2013.0
DRAFT_ROUND                  1.0
DRAFT_NUMBER                12.0
ROSTER_STATUS                1.0
PTS                          8.2
REB                          9.2
AST                          2.0
FROM_YEAR                   2013
TO_YEAR                     2020
Name: 2, dtype: object

In [109]:
keys = list('abcd')
data = [4, 2, 3, 100]
{keys[i]: val for i, val in enumerate(data) if i % 2 == 0}

{'a': 4, 'c': 3}

In [110]:
{n * n for n in [1, 1, 2, 2, 3, 3, 3]}

{1, 4, 9}

In [111]:
(n * n for n in [1, 1, 2, 2, 3, 3, 3])

In [112]:
import sys

In [113]:
li = [n * n for n in range(100000)]

In [114]:
sys.getsizeof(li)

800984

In [115]:
g = (n * n for n in range(100000))

In [116]:
sys.getsizeof(g)

112

In [117]:
type(g)

generator

In [118]:
type(li)

list

In [ ]:
{}
set()